version: '3'

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./mock/postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: example
      POSTGRES_PASSWORD: password