// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text" validate:"required"`
	UserID string `json:"userId" validate:"required"`
}

type Todo struct {
	ID     string `json:"id"`
	UserID *User  `json:"userId"`
	Name   string `json:"name"`
}
